name: Build Docker Python Image

on:
  push:
    branches: [ "mainr" ] 
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest  

    steps:

      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to our Docker Hub
        run: docker build -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build the Docker Python image
        run: docker build . --file dockerfile --tag tasneemdabash/final-python-project:${{ GITHUB.RUN_NUMBER }} -${{ GITHUB.SHA }}

      - name: Push this Docker Python image to our Docker Hub
        run: docker push yousifv/dockerfile:${{ GITHUB.RUN_NUMBER }} -${{ GITHUB.SHA }}
